apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    protocol: TCP
  selector:
    run: nginx
  type: LoadBalancer
